### ISSUE TITLE
upgrade to PROJ 8.x or 9.x

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/input-sdk#58]

**Comment by PeterPetrik** [comment]
@uclaros managed to build Input on debian-testing (proj8, qt5.15.x). Changes required:

Input-SDK: https://github.com/lutraconsulting/input-sdk/tree/debian-testing
Input-build: https://github.com/uclaros/QGIS/commit/2e8a3fb533de70bdd45c6e81862e910ce2f7f5a6
Input-PROJ: replace https://github.com/lutraconsulting/input/tree/master/app/android/assets/qgis-data with PROJ8 database

related to https://github.com/lutraconsulting/input/issues/620
maybe related to https://github.com/lutraconsulting/input/issues/1735

**Comment by uclaros** [comment]
More proper (properer?) fix for Input-build: https://github.com/lutraconsulting/input/commit/4b681b945fedc7b67a23ec769e095d5b83c26745

**Comment by PeterPetrik** [comment]
looks like proj-8 will be in the next LTR Ubuntu 22.04 | Jammy Jellyfish to be released in April 2022. So far even github do not have the machine available with this.
