### ISSUE TITLE
problem uploading geotiff

### ISSUE THREAD

**Issue by goos-github** [MerginMaps/input-sdk#76]
I work a lot with raster data. I work with Qgis on my PC, and then with Mergin Maps on the ipad.  When I upload a geotiff to MerginMaps, and then download it on my ipad, I get an error message when I want to display it. However, I do not get that problem when I upload the same file as a jpeg2000.
[test.zip](https://github.com/MerginMaps/input-sdk/files/9258005/test.zip)

**Comment by PeterPetrik** [comment]
if works on my iPhone with merginmaps input 1.6.0 without problem

try to test https://app.merginmaps.com/projects/peter.petrik/test_geotiff/tree

![IMG_022467F519CF-1](https://user-images.githubusercontent.com/804608/182810767-f4c3b52b-7e81-44ac-9c24-7749e2e01abd.jpeg)
